[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "argon2-cffi>=25.1.0",
    "django>=5.2,<5.3",
    "django-environ>=0.14.0",
    "djangorestframework>=3.18.3",
    "drf-spectacular>=0.30.0",
    "drf-spectacular-sidecar>=2026.10.1",
    "phonenumbers>=9.0.40",
    "psycopg[binary]>=3.3.6",
    "pyjwt>=2.15.1",
    "redis>=8.1.0",
]
