# Generated by Django 5.2.18 on 2026-10-06 17:40

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(editable=False, max_length=23, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('DOCTOR', 'Doctor'), ('OWNER', 'Owner')], max_length=8)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=128)),
                ('phone_country_code', models.CharField(default='EG', max_length=2)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_family_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('client_app', models.CharField(choices=[('HUB', 'Hub'), ('ADVISOR', 'Advisor')], max_length=7)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('remember_me', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'refresh_tokens',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='customer', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_birth', models.DateField()),
                ('pin_hash', models.CharField(max_length=255)),
                ('credential_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='doctor', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('password_hash', models.CharField(max_length=255)),
                ('professional_license_number', models.CharField(max_length=100, unique=True)),
                ('specialty', models.CharField(max_length=100)),
                ('clinic_name', models.CharField(max_length=200)),
                ('clinic_address', models.TextField()),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('mfa_secret_encrypted', models.TextField(blank=True, null=True)),
                ('mfa_enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('credential_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='owner', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('password_hash', models.CharField(max_length=255)),
                ('credential_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'owners',
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('account_type', 'phone_number'), name='users_account_type_phone_unique'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(models.F('account_type'), django.db.models.functions.text.Lower('email'), name='users_account_type_email_unique'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('account_type__in', ['CUSTOMER', 'DOCTOR', 'OWNER'])), name='users_account_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('is_staff', False), ('account_type', 'OWNER'), _connector='OR'), name='users_staff_requires_owner'),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='replaced_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaces', to='accounts.refreshtoken'),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('pin_hash', ''), _negated=True), name='customers_pin_hash_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='owner',
            constraint=models.CheckConstraint(condition=models.Q(('password_hash', ''), _negated=True), name='owners_password_hash_not_empty'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='reviewed_by_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_doctors', to='accounts.owner'),
        ),
        migrations.AddConstraint(
            model_name='refreshtoken',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='refresh_tokens_expiry_valid'),
        ),
        migrations.AddConstraint(
            model_name='refreshtoken',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('replaced_by_id')), _negated=True), name='refresh_tokens_no_self_replacement'),
        ),
        migrations.AddConstraint(
            model_name='refreshtoken',
            constraint=models.CheckConstraint(condition=models.Q(('client_app__in', ['HUB', 'ADVISOR'])), name='refresh_tokens_client_app_valid'),
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.CheckConstraint(condition=models.Q(('password_hash', ''), _negated=True), name='doctors_password_hash_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.CheckConstraint(condition=models.Q(('approval_status__in', ['PENDING', 'APPROVED', 'REJECTED'])), name='doctors_approval_status_valid'),
        ),
    ]
