# Generated by Django 5.2.18 on 2026-10-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE SEQUENCE have_user_id_seq
                AS bigint
                START WITH 1
                INCREMENT BY 1
                MINVALUE 1
                MAXVALUE 999999999999
                NO CYCLE;
            """,
            reverse_sql="DROP SEQUENCE have_user_id_seq;",
        ),
    ]
