# Generated by Django 5.2.18 on 2026-10-06 17:44

from django.db import migrations

CHECK_PROFILE_SQL = """
CREATE FUNCTION have_check_user_profile()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    target_user_id varchar;
    target_account_type varchar;
    profile_count integer;
    matching_profile_exists boolean;
BEGIN
    IF TG_TABLE_NAME = 'users' THEN
        target_user_id := NEW.id;
    ELSIF TG_OP = 'DELETE' THEN
        target_user_id := OLD.user_id;
    ELSE
        target_user_id := NEW.user_id;
    END IF;

    SELECT account_type
    INTO target_account_type
    FROM users
    WHERE id = target_user_id;

    IF NOT FOUND THEN
        RETURN NULL;
    END IF;

    SELECT
        (SELECT COUNT(*) FROM customers WHERE user_id = target_user_id)
        + (SELECT COUNT(*) FROM doctors WHERE user_id = target_user_id)
        + (SELECT COUNT(*) FROM owners WHERE user_id = target_user_id)
    INTO profile_count;

    SELECT CASE target_account_type
        WHEN 'CUSTOMER' THEN EXISTS (
            SELECT 1 FROM customers WHERE user_id = target_user_id
        )
        WHEN 'DOCTOR' THEN EXISTS (
            SELECT 1 FROM doctors WHERE user_id = target_user_id
        )
        WHEN 'OWNER' THEN EXISTS (
            SELECT 1 FROM owners WHERE user_id = target_user_id
        )
        ELSE FALSE
    END
    INTO matching_profile_exists;

    IF profile_count <> 1 OR NOT matching_profile_exists THEN
        RAISE EXCEPTION
            'User must have exactly one profile matching its account type'
            USING ERRCODE = '23514';
    END IF;

    RETURN NULL;
END;
$$;
"""

PROFILE_TRIGGERS_SQL = """
CREATE CONSTRAINT TRIGGER have_users_profile_check
AFTER INSERT OR UPDATE ON users
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION have_check_user_profile();

CREATE CONSTRAINT TRIGGER have_customers_profile_check
AFTER INSERT OR UPDATE OR DELETE ON customers
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION have_check_user_profile();

CREATE CONSTRAINT TRIGGER have_doctors_profile_check
AFTER INSERT OR UPDATE OR DELETE ON doctors
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION have_check_user_profile();

CREATE CONSTRAINT TRIGGER have_owners_profile_check
AFTER INSERT OR UPDATE OR DELETE ON owners
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION have_check_user_profile();
"""

IMMUTABLE_IDENTITY_SQL = """
CREATE FUNCTION have_protect_user_identity()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.id IS DISTINCT FROM OLD.id
       OR NEW.account_type IS DISTINCT FROM OLD.account_type THEN
        RAISE EXCEPTION
            'User ID and account type cannot be changed'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER have_users_identity_immutable
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION have_protect_user_identity();


CREATE FUNCTION have_protect_profile_identity()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.user_id IS DISTINCT FROM OLD.user_id THEN
        RAISE EXCEPTION
            'A credential profile cannot be moved to another user'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER have_customers_identity_immutable
BEFORE UPDATE ON customers
FOR EACH ROW
EXECUTE FUNCTION have_protect_profile_identity();

CREATE TRIGGER have_doctors_identity_immutable
BEFORE UPDATE ON doctors
FOR EACH ROW
EXECUTE FUNCTION have_protect_profile_identity();

CREATE TRIGGER have_owners_identity_immutable
BEFORE UPDATE ON owners
FOR EACH ROW
EXECUTE FUNCTION have_protect_profile_identity();
"""

REVERSE_SQL = """
DROP TRIGGER have_users_profile_check ON users;
DROP TRIGGER have_customers_profile_check ON customers;
DROP TRIGGER have_doctors_profile_check ON doctors;
DROP TRIGGER have_owners_profile_check ON owners;
DROP FUNCTION have_check_user_profile();

DROP TRIGGER have_users_identity_immutable ON users;
DROP FUNCTION have_protect_user_identity();

DROP TRIGGER have_customers_identity_immutable ON customers;
DROP TRIGGER have_doctors_identity_immutable ON doctors;
DROP TRIGGER have_owners_identity_immutable ON owners;
DROP FUNCTION have_protect_profile_identity();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_id_sequence'),
    ]

    operations = [
            migrations.RunSQL(
                sql=(
                    CHECK_PROFILE_SQL
                    + PROFILE_TRIGGERS_SQL
                    + IMMUTABLE_IDENTITY_SQL
                ),
                reverse_sql=REVERSE_SQL,
            ),
        ]
