# Generated by Django 5.2.18 on 2026-10-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_integrity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='professional_license_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.UniqueConstraint(fields=('professional_license_number',), name='doctors_license_number_unique'),
        ),
    ]
